### ISSUE TITLE
Altstore: This action cannot be completed at this time (-22411)

### ISSUE THREAD

**Issue by parkjaeil0x01** [dreth/Altserver-docker#6]
# What I need only is
- A feature for refreshing apps through a WiFi

# What I faced at
- Do refreshing apps then got an error(This action cannot be completed at this time (-22411))

---

# Configurations and Logs

## docker-compose.yml
```yaml
version: '3.8'

services:
  altserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: altserver
    volumes:
      - "./lib:/root/.config/Provision/lib"
      - "./bin:/altserver/bin"
      - "./logs:/altserver/logs"
      - "/dev/bus/usb:/dev/bus/usb"
      - "/var/lib/lockdown:/var/lib/lockdown"
      - "/var/run:/var/run"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    network_mode: host
    # Optional environment variables to override the default architecture
    # for the altserver, netmuxd, and anisette binaries.
    environment:
      - OVERRIDE_ALTSERVER_ARCH=arm64-v8a
      - OVERRIDE_NETMUXD_ARCH=arm64-v8a
      - OVERRIDE_ANISETTE_ARCH=arm64-v8a
      - OVERRIDE_PROVISION_LIBS_ARCH=arm64-v8a
      - ALLOW_PROVISION_TO_DOWNLOAD_LIBS=true
    privileged: true
    restart: unless-stopped

```

## cat /proc/cpuinfo
```shell
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2835
Revision        : c03112
Serial          : 10000000f2c4f220
Model           : Raspberry Pi 4 Model B Rev 1.2
```

## uname -m
```shell
aarch64
```

## docker logs
```shell
Getting binaries...
AltStore is up to date.
AltServer is up to date.
netmuxd is up to date.
anisette-server is up to date.
Making scripts executable...
Starting avahi-daemon service...
Purging logs...
Skipping decompressing required libs for Provision...
Starting supervisord...
2024-08-28 16:34:50,264 INFO Set uid to user 0 succeeded
2024-08-28 16:34:50,292 INFO RPC interface 'supervisor' initialized
2024-08-28 16:34:50,292 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-08-28 16:34:50,294 INFO supervisord started with pid 1
2024-08-28 16:34:51,300 INFO spawned: 'usbmuxd' with pid 67
2024-08-28 16:34:51,307 INFO spawned: 'anisette-server' with pid 68
2024-08-28 16:34:51,313 INFO spawned: 'netmuxd' with pid 69
2024-08-28 16:34:51,320 INFO spawned: 'altserver' with pid 70
2024-08-28 16:34:52,621 INFO success: usbmuxd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-08-28 16:34:52,621 INFO success: anisette-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-08-28 16:34:52,622 INFO success: netmuxd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-08-28 16:34:52,622 INFO success: altserver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

## tail -n 100 logs/altserver.err.log
```shell
*** WARNING *** The program 'python3.11' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
```

## tail -n 100 logs/altserver.out.log
```shell
Finished handling request!
Other Socket:7. Port: 55155. Error: 0
Receiving request size...
Checking socket: 7
Received bytes: 4(of 4)
Receiving 48 bytes...
Checking socket: 7
Received bytes: 48(of 48)
Received response status code: 200
parse anisette data ret
Got anisetteData json: {"X-Apple-I-Client-Time":"2024-08-28T16:37:08Z","X-Apple-I-MD":"[REDACTED]","X-Apple-I-MD-LU":"[REDACTED]","X-Apple-I-MD-M":"[REDACTED]","X-Apple-I-MD-RINFO":"17106176","X-Apple-I-SRL-NO":"0","X-Apple-I-TimeZone":"UTC","X-Apple-Locale":"en_US","X-MMe-Client-Info":"<MacBookPro13,2> <macOS;13.1;22C65> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>","X-Mme-Device-Id":"[REDACTED]"}
X-Apple-I-MD-M: [REDACTED]
X-Apple-I-MD: [REDACTED]
X-Apple-I-MD-LU: [REDACTED]
X-Apple-I-MD-RINFO: 17106176
X-Mme-Device-Id: [REDACTED]
X-Apple-I-SRL-NO: 0
X-MMe-Client-Info: <MacBookPro13,2> <macOS;13.1;22C65> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>
X-Apple-I-Client-Time: 2024-08-28T16:37:08Z
X-Apple-Locale: en_US
X-Apple-I-TimeZone: UTC
Building anisetteData obj...
MachineID : [REDACTED]
One-Time Password: [REDACTED]
Local User ID: [REDACTED]
Device UDID: [REDACTED]
Device Description: <MacBookPro13,2> <macOS;13.1;22C65> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>
Date: 2024-08-28T16:37:08Z
Represented Value: 592
Sent Bytes Count: 4 (4)
Sent Data: 4 Bytes
Sent Bytes Count: 592 (592)
Sent Data: 592 Bytes
Finished handling request!
Other Socket:7. Port: 55157. Error: 0
Receiving request size...
```
